# 设置基础镜像
# FROM d40

# 安装 socket-node
# RUN git clone https://github.com/dancerphil/socket-node.git .

# 由于私有项目需要证书，证书好麻烦，使用 commit
# docker run -i -t d40 /bin/bash
# git clone https://github.com/dancerphil/socket-node.git .
# Username for 'https://github.com': dancerphil
# Password for 'https://dancerphil@github.com': ******
# exit
# docker ps -l
# docker commit 851d6449f3e0 c41
